### ISSUE TITLE
Interface Interactions

### ISSUE THREAD

**Issue by tayrosby** [tayrosby/sales-app#19]

**Comment by MSillanp** [comment]
Interface Interactions
	
Depending on budget constraints, the system could potentially interface with 3rd party APIs via Spring based REST services. One service would make a call to an API to pull tax based off a certain zip code, using services such as those offered by Tax Jar, AvaTax, Ziptax, or Taxee. Another service can interface with payment APIs such as PayPal. Since tax APIs are costly to use, the application may alternatively use downloaded tax files supplied for free and load those into an SQL database. 

The application will also need to interface with technologies from other companies whose business is tied to ours. The application will need to be able to fetch billing and shipping information (such as addresses, shipping rates, and arrival times) from shipping companies such as UPS and FedEx. It will also need to gather information about potential stock, delivery times, and item details from different suppliers and warehouses.

**Comment by MSillanp** [comment]
Issue is added to main document
